### Data Cleaning
The goal of this phase was to prepare the diabetes dataset for exploratory data analysis and modeling by addressing missing values, removing unnecessary variables, and ensuring data quality.

Data Cleaning Procedures
-Replaced placeholder values (?) with missing values (NaN).
-Removed identifier variables (encounter_id, patient_nbr).
-Removed variables with excessive missingness (weight, payer_code, medical_specialty).
-Removed observations with invalid gender, race and medical diagnodid classifications.
-Checked for duplicate records and removed them
-Retained variables relevant to the research questions on readmission

| Dataset Stage    |    Rows | Columns |
| ---------------- | ------: | ------: |
| Original Dataset | 101,766 |      50 |
| Cleaned Dataset  |  71,518 |     44 |

After data cleaning, the dataset was reduced from 101,766 observations to 71,518 observations. Records were removed due to duplicate patient encounters and the exclusion of variables with excessive missing values.

| Readmission Status | Percentage |
| ------------------ | ---------: |
| NO                 |     60.10% |
| >30                |     31.10% |
| <30                |      8.80% |

The majority of patients (60.10%) were not readmitted after discharge. Approximately 31.10% were readmitted after 30 days, while only 8.80% were readmitted within 30 days. This indicates that the dataset is somewhat imbalanced.




Due to the extremely high proportion of missing data, Weight will likely be excluded from further analysis. Variables with moderate missingness will be evaluated on a case-by-case basis.

In [17]:
import pandas as pd

df = pd.read_csv("../data/diabetic_data.csv")

Dataset Inspection

In [18]:
df.shape
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    101766 non-null  object
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  object
 19  diag_2                    101766 non-null  object
 20  diag_3                    101766 non-null  object
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    object
 23  A1Cresult                 17018 non-null   object
 24  metformin                 101766 non-null  object
 25  repaglinide               101766 non-null  object
 26  nateglinide               101766 non-null  object
 27  chlorpropamide            101766 non-null  object
 28  glimepiride               101766 non-null  object
 29  acetohexamide             101766 non-null  object
 30  glipizide                 101766 non-null  object
 31  glyburide                 101766 non-null  object
 32  tolbutamide               101766 non-null  object
 33  pioglitazone              101766 non-null  object
 34  rosiglitazone             101766 non-null  object
 35  acarbose                  101766 non-null  object
 36  miglitol                  101766 non-null  object
 37  troglitazone              101766 non-null  object
 38  tolazamide                101766 non-null  object
 39  examide                   101766 non-null  object
 40  citoglipton               101766 non-null  object
 41  insulin                   101766 non-null  object
 42  glyburide-metformin       101766 non-null  object
 43  glipizide-metformin       101766 non-null  object
 44  glimepiride-pioglitazone  101766 non-null  object
 45  metformin-rosiglitazone   101766 non-null  object
 46  metformin-pioglitazone    101766 non-null  object
 47  change                    101766 non-null  object
 48  diabetesMed               101766 non-null  object
 49  readmitted                101766 non-null  object
dtypes: int64(13), object(37)
memory usage: 38.8+ MB

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,1.017660e+05,1.017660e+05,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,1.652016e+08,5.433040e+07,2.024006,3.715642,5.754437,4.395987,43.095641,1.339730,16.021844,0.369357,0.197836,0.635566,7.422607
std,1.026403e+08,3.869636e+07,1.445403,5.280166,4.064081,2.985108,19.674362,1.705807,8.127566,1.267265,0.930472,1.262863,1.933600
min,1.252200e+04,1.350000e+02,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,8.496119e+07,2.341322e+07,1.000000,1.000000,1.000000,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,1.523890e+08,4.550514e+07,1.000000,1.000000,7.000000,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,2.302709e+08,8.754595e+07,3.000000,4.000000,7.000000,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,4.438672e+08,1.895026e+08,8.000000,28.000000,25.000000,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

Missing values

In [19]:
(df == "?").sum().sort_values(ascending=False)

weight                      98569
medical_specialty           49949
payer_code                  40256
race                         2273
diag_3                       1423
diag_2                        358
diag_1                         21
admission_type_id               0
patient_nbr                     0
encounter_id                    0
time_in_hospital                0
admission_source_id             0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
discharge_disposition_id        0
gender                          0
age                             0
number_inpatient                0
number_emergency                0
number_outpatient               0
number_diagnoses                0
max_glu_serum                   0
A1Cresult                       0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

Replace ?

In [20]:
import numpy as np

df.replace("?", np.nan, inplace=True)

df.isnull().sum().sort_values(ascending=False)

weight                      98569
max_glu_serum               96420
A1Cresult                   84748
medical_specialty           49949
payer_code                  40256
race                         2273
diag_3                       1423
diag_2                        358
diag_1                         21
patient_nbr                     0
time_in_hospital                0
admission_source_id             0
num_lab_procedures              0
encounter_id                    0
admission_type_id               0
discharge_disposition_id        0
gender                          0
age                             0
number_inpatient                0
number_emergency                0
number_outpatient               0
num_medications                 0
num_procedures                  0
number_diagnoses                0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

Drop columns w/ missing data
Weight, maximum glucose in blood serum, A1C result, medical specialty and payer codes have over 40k missing data so they are being removed for this analysis. This is to improve data quality and reduce potential bias introduced.

In [21]:
df.drop(columns=[
    "weight",
    "max_glu_serum",
    "A1Cresult",
    "medical_specialty",
    "payer_code"
], inplace=True)

Remove duplicate patients
Duplicate patient records were removed to ensure independence among observations.

In [22]:
df = df.drop_duplicates(subset="patient_nbr")

Remove identifiers

In [23]:
df.drop(columns=[
    "encounter_id",
    "patient_nbr"
], inplace=True)

Confirm no blanks?

In [24]:
df.isnull().sum()

race                        1948
gender                         0
age                            0
admission_type_id              0
discharge_disposition_id       0
admission_source_id            0
time_in_hospital               0
num_lab_procedures             0
num_procedures                 0
num_medications                0
number_outpatient              0
number_emergency               0
number_inpatient               0
diag_1                        11
diag_2                       294
diag_3                      1225
number_diagnoses               0
metformin                      0
repaglinide                    0
nateglinide                    0
chlorpropamide                 0
glimepiride                    0
acetohexamide                  0
glipizide                      0
glyburide                      0
tolbutamide                    0
pioglitazone                   0
rosiglitazone                  0
acarbose                       0
miglitol                       0
troglitazone                   0
tolazamide                     0
examide                        0
citoglipton                    0
insulin                        0
glyburide-metformin            0
glipizide-metformin            0
glimepiride-pioglitazone       0
metformin-rosiglitazone        0
metformin-pioglitazone         0
change                         0
diabetesMed                    0
readmitted                     0
dtype: int64

Race missing values

In [25]:
df["race"] = df["race"].fillna("Unknown")

Diagnosi code missing values

In [26]:
df["diag_1"] = df["diag_1"].fillna("Unknown")
df["diag_2"] = df["diag_2"].fillna("Unknown")
df["diag_3"] = df["diag_3"].fillna("Unknown")

Binary Readmissions

In [27]:
df["readmitted_binary"] = df["readmitted"].apply(
    lambda x: 1 if x == "<30" else 0
)

Class balance

In [28]:
df["readmitted_binary"].value_counts()

readmitted_binary
0    65225
1     6293
Name: count, dtype: int64

In [29]:
df["readmitted_binary"].value_counts(normalize=True)*100

readmitted_binary
0    91.200817
1     8.799183
Name: proportion, dtype: float64

Saving clean dataset

In [30]:
df.to_csv(
    "diabetes_cleaned.csv",
    index=False
)

In [31]:
df["readmitted"].value_counts()
df["readmitted"].value_counts(normalize=True) * 100

readmitted
NO     60.103750
>30    31.097066
<30     8.799183
Name: proportion, dtype: float64

In [32]:
df.shape
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 71518 entries, 0 to 101765
Data columns (total 44 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   race                      71518 non-null  object
 1   gender                    71518 non-null  object
 2   age                       71518 non-null  object
 3   admission_type_id         71518 non-null  int64
 4   discharge_disposition_id  71518 non-null  int64
 5   admission_source_id       71518 non-null  int64
 6   time_in_hospital          71518 non-null  int64
 7   num_lab_procedures        71518 non-null  int64
 8   num_procedures            71518 non-null  int64
 9   num_medications           71518 non-null  int64
 10  number_outpatient         71518 non-null  int64
 11  number_emergency          71518 non-null  int64
 12  number_inpatient          71518 non-null  int64
 13  diag_1                    71518 non-null  object
 14  diag_2                    71518 non-null  object
 15  diag_3                    71518 non-null  object
 16  number_diagnoses          71518 non-null  int64
 17  metformin                 71518 non-null  object
 18  repaglinide               71518 non-null  object
 19  nateglinide               71518 non-null  object
 20  chlorpropamide            71518 non-null  object
 21  glimepiride               71518 non-null  object
 22  acetohexamide             71518 non-null  object
 23  glipizide                 71518 non-null  object
 24  glyburide                 71518 non-null  object
 25  tolbutamide               71518 non-null  object
 26  pioglitazone              71518 non-null  object
 27  rosiglitazone             71518 non-null  object
 28  acarbose                  71518 non-null  object
 29  miglitol                  71518 non-null  object
 30  troglitazone              71518 non-null  object
 31  tolazamide                71518 non-null  object
 32  examide                   71518 non-null  object
 33  citoglipton               71518 non-null  object
 34  insulin                   71518 non-null  object
 35  glyburide-metformin       71518 non-null  object
 36  glipizide-metformin       71518 non-null  object
 37  glimepiride-pioglitazone  71518 non-null  object
 38  metformin-rosiglitazone   71518 non-null  object
 39  metformin-pioglitazone    71518 non-null  object
 40  change                    71518 non-null  object
 41  diabetesMed               71518 non-null  object
 42  readmitted                71518 non-null  object
 43  readmitted_binary         71518 non-null  int64
dtypes: int64(12), object(32)
memory usage: 24.6+ MB

,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,readmitted_binary
count,71518.000000,71518.000000,71518.000000,71518.00000,71518.000000,71518.000000,71518.000000,71518.000000,71518.000000,71518.000000,71518.000000,71518.000000
mean,2.100254,3.593235,5.657457,4.28913,43.075478,1.430577,15.705025,0.280069,0.103540,0.177829,7.245700,0.087992
std,1.508301,5.269771,4.162580,2.94921,19.952338,1.759864,8.311163,1.068957,0.509187,0.603790,1.994674,0.283285
min,1.000000,1.000000,1.000000,1.00000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,1.000000,1.000000,1.000000,2.00000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000,0.000000
50%,1.000000,1.000000,7.000000,3.00000,44.000000,1.000000,14.000000,0.000000,0.000000,0.000000,8.000000,0.000000
75%,3.000000,3.000000,7.000000,6.00000,57.000000,2.000000,20.000000,0.000000,0.000000,0.000000,9.000000,0.000000
max,8.000000,28.000000,25.000000,14.00000,132.000000,6.000000,81.000000,42.000000,42.000000,12.000000,16.000000,1.000000